/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dp_oppai_PPCalc */

#ifndef _Included_dp_oppai_PPCalc
#define _Included_dp_oppai_PPCalc
#ifdef __cplusplus
extern "C" {
#endif
#undef dp_oppai_PPCalc_DEFAULT_COMBO
#define dp_oppai_PPCalc_DEFAULT_COMBO -1L
#undef dp_oppai_PPCalc_DEFAULT_MISSES
#define dp_oppai_PPCalc_DEFAULT_MISSES 0L
#undef dp_oppai_PPCalc_DEFAULT_C300
#define dp_oppai_PPCalc_DEFAULT_C300 -1L
#undef dp_oppai_PPCalc_DEFAULT_C100
#define dp_oppai_PPCalc_DEFAULT_C100 0L
#undef dp_oppai_PPCalc_DEFAULT_C50
#define dp_oppai_PPCalc_DEFAULT_C50 0L
#undef dp_oppai_PPCalc_DEFAULT_SCORE_VER
#define dp_oppai_PPCalc_DEFAULT_SCORE_VER 1L
#undef dp_oppai_PPCalc_DEFAULT_ACCURACY
#define dp_oppai_PPCalc_DEFAULT_ACCURACY 100.0
/*
 * Class:     dp_oppai_PPCalc
 * Method:    nativeCalcPP
 * Signature: (Ldp/oppai/Beatmap;Ldp/oppai/OppaiCtx;DDIIIIIII)V
 */
JNIEXPORT void JNICALL Java_dp_oppai_PPCalc_nativeCalcPP
  (JNIEnv *, jobject, jobject, jobject, jdouble, jdouble, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     dp_oppai_PPCalc
 * Method:    nativeCalcPPAcc
 * Signature: (Ldp/oppai/Beatmap;Ldp/oppai/OppaiCtx;DDDIIII)V
 */
JNIEXPORT void JNICALL Java_dp_oppai_PPCalc_nativeCalcPPAcc
  (JNIEnv *, jobject, jobject, jobject, jdouble, jdouble, jdouble, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
