/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dp_oppai_Buffer */

#ifndef _Included_dp_oppai_Buffer
#define _Included_dp_oppai_Buffer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dp_oppai_Buffer
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dp_oppai_Buffer_dispose
  (JNIEnv *, jobject);

/*
 * Class:     dp_oppai_Buffer
 * Method:    newBuffer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_dp_oppai_Buffer_newBuffer
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
