/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dp_oppai_DiffCalc */

#ifndef _Included_dp_oppai_DiffCalc
#define _Included_dp_oppai_DiffCalc
#ifdef __cplusplus
extern "C" {
#endif
#undef dp_oppai_DiffCalc_DEFAULT_SINGLETAP_THRESHOLD
#define dp_oppai_DiffCalc_DEFAULT_SINGLETAP_THRESHOLD 125L
/*
 * Class:     dp_oppai_DiffCalc
 * Method:    nativeDiffCalc
 * Signature: (Ldp/oppai/Beatmap;Ldp/oppai/OppaiCtx;ZZZZI)V
 */
JNIEXPORT void JNICALL Java_dp_oppai_DiffCalc_nativeDiffCalc
  (JNIEnv *, jobject, jobject, jobject, jboolean, jboolean, jboolean, jboolean, jint);

#ifdef __cplusplus
}
#endif
#endif
