/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dp_oppai_OppaiCtx */

#ifndef _Included_dp_oppai_OppaiCtx
#define _Included_dp_oppai_OppaiCtx
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dp_oppai_OppaiCtx
 * Method:    newCtx
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dp_oppai_OppaiCtx_newCtx
  (JNIEnv *, jobject);

/*
 * Class:     dp_oppai_OppaiCtx
 * Method:    newDiffCalcContext
 * Signature: (Ldp/oppai/OppaiCtx;)V
 */
JNIEXPORT void JNICALL Java_dp_oppai_OppaiCtx_newDiffCalcContext
  (JNIEnv *, jobject, jobject);

/*
 * Class:     dp_oppai_OppaiCtx
 * Method:    nativeGetLastErr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_dp_oppai_OppaiCtx_nativeGetLastErr
  (JNIEnv *, jobject);

/*
 * Class:     dp_oppai_OppaiCtx
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dp_oppai_OppaiCtx_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
