/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dp_oppai_Beatmap */

#ifndef _Included_dp_oppai_Beatmap
#define _Included_dp_oppai_Beatmap
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     dp_oppai_Beatmap
	* Method:    getCS
	* Signature: ()F
	*/
	JNIEXPORT jfloat JNICALL Java_dp_oppai_Beatmap_getCS
	(JNIEnv *, jobject);

	/*
	* Class:     dp_oppai_Beatmap
	* Method:    getOD
	* Signature: ()F
	*/
	JNIEXPORT jfloat JNICALL Java_dp_oppai_Beatmap_getOD
	(JNIEnv *, jobject);

	/*
	* Class:     dp_oppai_Beatmap
	* Method:    getAR
	* Signature: ()F
	*/
	JNIEXPORT jfloat JNICALL Java_dp_oppai_Beatmap_getAR
	(JNIEnv *, jobject);

	/*
	* Class:     dp_oppai_Beatmap
	* Method:    getHP
	* Signature: ()F
	*/
	JNIEXPORT jfloat JNICALL Java_dp_oppai_Beatmap_getHP
	(JNIEnv *, jobject);

	/*
	* Class:     dp_oppai_Beatmap
	* Method:    setCS
	* Signature: (F)V
	*/
	JNIEXPORT void JNICALL Java_dp_oppai_Beatmap_setCS
	(JNIEnv *, jobject, jfloat);

	/*
	* Class:     dp_oppai_Beatmap
	* Method:    setOD
	* Signature: (F)V
	*/
	JNIEXPORT void JNICALL Java_dp_oppai_Beatmap_setOD
	(JNIEnv *, jobject, jfloat);

	/*
	* Class:     dp_oppai_Beatmap
	* Method:    setAR
	* Signature: (F)V
	*/
	JNIEXPORT void JNICALL Java_dp_oppai_Beatmap_setAR
	(JNIEnv *, jobject, jfloat);

	/*
	* Class:     dp_oppai_Beatmap
	* Method:    getArtist
	* Signature: ()Ljava/lang/String;
	*/
	JNIEXPORT jstring JNICALL Java_dp_oppai_Beatmap_getArtist
	(JNIEnv *, jobject);

	/*
	* Class:     dp_oppai_Beatmap
	* Method:    getTitle
	* Signature: ()Ljava/lang/String;
	*/
	JNIEXPORT jstring JNICALL Java_dp_oppai_Beatmap_getTitle
	(JNIEnv *, jobject);

	/*
	* Class:     dp_oppai_Beatmap
	* Method:    getVersion
	* Signature: ()Ljava/lang/String;
	*/
	JNIEXPORT jstring JNICALL Java_dp_oppai_Beatmap_getVersion
	(JNIEnv *, jobject);

	/*
	* Class:     dp_oppai_Beatmap
	* Method:    getCreator
	* Signature: ()Ljava/lang/String;
	*/
	JNIEXPORT jstring JNICALL Java_dp_oppai_Beatmap_getCreator
	(JNIEnv *, jobject);

	/*
	* Class:     dp_oppai_Beatmap
	* Method:    getNumObjects
	* Signature: ()I
	*/
	JNIEXPORT jint JNICALL Java_dp_oppai_Beatmap_getNumObjects
	(JNIEnv *, jobject);

	/*
	* Class:     dp_oppai_Beatmap
	* Method:    getNumCircles
	* Signature: ()I
	*/
	JNIEXPORT jint JNICALL Java_dp_oppai_Beatmap_getNumCircles
	(JNIEnv *, jobject);

	/*
	* Class:     dp_oppai_Beatmap
	* Method:    getNumSliders
	* Signature: ()I
	*/
	JNIEXPORT jint JNICALL Java_dp_oppai_Beatmap_getNumSliders
	(JNIEnv *, jobject);

	/*
	* Class:     dp_oppai_Beatmap
	* Method:    getNumSpinners
	* Signature: ()I
	*/
	JNIEXPORT jint JNICALL Java_dp_oppai_Beatmap_getNumSpinners
	(JNIEnv *, jobject);

	/*
	* Class:     dp_oppai_Beatmap
	* Method:    getMaxCombo
	* Signature: ()I
	*/
	JNIEXPORT jint JNICALL Java_dp_oppai_Beatmap_getMaxCombo
	(JNIEnv *, jobject);

	/*
	* Class:     dp_oppai_Beatmap
	* Method:    getMode
	* Signature: ()S
	*/
	JNIEXPORT jshort JNICALL Java_dp_oppai_Beatmap_getMode
	(JNIEnv *, jobject);

	/*
	* Class:     dp_oppai_Beatmap
	* Method:    applyMods
	* Signature: (I)V
	*/
	JNIEXPORT void JNICALL Java_dp_oppai_Beatmap_applyMods
	(JNIEnv *, jobject, jint);

	/*
	* Class:     dp_oppai_Beatmap
	* Method:    dispose
	* Signature: ()V
	*/
	JNIEXPORT void JNICALL Java_dp_oppai_Beatmap_dispose
	(JNIEnv *, jobject);

	/*
	* Class:     dp_oppai_Beatmap
	* Method:    newBeatmap
	* Signature: (Ldp/oppai/OppaiCtx;)V
	*/
	JNIEXPORT void JNICALL Java_dp_oppai_Beatmap_newBeatmap
	(JNIEnv *, jobject, jobject);

	/*
	* Class:     dp_oppai_Beatmap
	* Method:    nativeParse
	* Signature: (Ljava/lang/String;Ldp/oppai/Buffer;IZLjava/lang/String;)V
	*/
	JNIEXPORT void JNICALL Java_dp_oppai_Beatmap_nativeParse
	(JNIEnv *, jobject, jstring, jobject, jint, jboolean, jstring);

#ifdef __cplusplus
}
#endif
#endif
